version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    build:
      context: .
      dockerfile: postgres_db/Dockerfile
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    init: true

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - postgres
    env_file: .env

volumes:
  postgres_data:
    name: postgres_data
