version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: bebigel
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    init: true

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: bebigel@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: admin42
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: postgres_data

# docker-compose up -d
# docker exec -it postgres sh
# psql -U bebigel -d piscineds -h localhost -W
# localhost:8080 to connect to pgadmin
